### ISSUE TITLE
homebrew installation fails with SHA mismatch

### ISSUE THREAD

**Issue by stulevine** [pact-foundation/homebrew-pact-ruby-standalone#18] opened 2020-08-18 15:12 UTC
+ brew cleanup -s
+ brew tap pact-foundation/pact-ruby-standalone
==> Tapping pact-foundation/pact-ruby-standalone
Cloning into '/usr/local/Homebrew/Library/Taps/pact-foundation/homebrew-pact-ruby-standalone'...
Tapped 1 formula (35 files, 32.5KB).
+ brew install pact-ruby-standalone
==> Installing pact-ruby-standalone from pact-foundation/pact-ruby-standalone
==> Downloading https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.3/pact-1.88.3-osx.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/92879052/8ab25100-dcfd-11ea-872b-a9608fff5d8a?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[REDACTED]&X-Amz-Expires=300&X-Amz-Signature=[REDACTED]=host&actor_id=0&repo_id=92879052&response-content-disposition=attachment%3B%20filename%3Dpact-1.88.3-osx.tar.gz&response-content-type=application%2Foctet-stream
Error: SHA256 mismatch
Expected: b52cfc7c2e405c26d426f817961d9816c7e57ded
  Actual: 90ad65d18890ffa5020e3c8cec8593f3c88da9ed1454873ba1fc0ce5dcc569fb
 Archive: /Users/vagrant/Library/Caches/Homebrew/downloads/b6141235269079a7b49a9bc536310e25fa56cf2e6dff1bc86d3a1d74f5101a7f--pact-1.88.3-osx.tar.gz

**Comment by bethesque** [comment] 2020-08-18 23:01
@surpher I updated to 1.88.3 using the update tap script. I can't work out why the SHA was wrong. Any thoughts?

**Comment by bethesque** [comment] 2020-08-18 23:02
Here's the difference between what it is and what the script says it should be https://github.com/pact-foundation/homebrew-pact-ruby-standalone/compare/version/v1.88.3

**Comment by bethesque** [comment] 2020-08-18 23:15
It's fixed btw @stulevine but I'd like to get to the root cause before closing the issue.

**Comment by stulevine** [comment] 2020-08-19 11:07
Thank you @bethesque.  I noticed my CI/CD pipelines are working properly again.

**Comment by surpher** [comment] 2021-02-02 03:19
The `openssl dgst` was using `sha1` at the time. It seems it has been changed to `sha256` a while back.

**Closed** 2021-02-15 00:19 UTC
